maps/jail_republic_csbr.bsp
maps/jail_republic_csbr.txt
sound/kozen/aiseeutepego.wav
sound/kozen/desertrain.wav
sound/kozen/todepauduro.wav
models/kozen/bebedouro.mdl
models/kozen/cadeira_de_bar.mdl
models/kozen/cadeira_de_piscina2.mdl
models/kozen/cama.mdl
models/kozen/chuveiros_enferrujados.mdl
models/kozen/cigarro.mdl
models/kozen/dinheiro.mdl
models/kozen/fonte.mdl
models/kozen/grama.mdl
models/kozen/lampadas.mdl
models/kozen/maquina_de_cafe.mdl
models/kozen/marlboro.mdl
models/kozen/mictorio.mdl
models/kozen/palmeira.mdl
models/kozen/skol.mdl
models/kozen/sofa.mdl