models/brgames_maps/cagelight01.mdl
sound/brgames_maps/brg_cps_woupi.wav
sound/brgames_maps/brg_cps_haha.wav
sound/play4ever_maps/musicas/thisislove.wav
sprites/laserbeam.spr
models/projetocs_maps/barstool.mdl
models/projetocs_maps/planta_pcs.mdl
models/projetocs_maps/table_bar_pcs.mdl
models/projetocs_maps/tab_lip_piano_pcs.mdl
models/projetocs_maps/garafa2_pcs.mdl
models/projetocs_maps/garafa_pcs.mdl
models/play4ever_maps/props/arvore_enorme.mdl
models/play4ever_maps/props/gramadinho2.mdl
models/play4ever_maps/props/arvore_palmeira.mdl
models/play4ever_maps/props/gramadinho1.mdl
maps/jail_xmf_b3_projetocs.res
maps/jail_xmf_b3_projetocs.bsp
maps/jail_xmf_b3_projetocs.txt
gfx/env/nebo5lf.tga
gfx/env/nebo5rf.tga
gfx/env/nebo5up.tga
gfx/env/nebo5bk.tga
gfx/env/nebo5dn.tga
gfx/env/nebo5ft.tga
