gfx/env/jail_futurebk.tga
gfx/env/jail_futuredn.tga
gfx/env/jail_futureft.tga
gfx/env/jail_futurelf.tga
gfx/env/jail_futurert.tga
gfx/env/jail_futureup.tga
maps/jail_future.bsp
maps/jail_future.res
maps/jail_future.txt
models/jail_future/ak47.mdl
models/jail_future/arbol.mdl
models/jail_future/awp.mdl
models/jail_future/bandera.mdl
models/jail_future/colchon.mdl
models/jail_future/fb.mdl
models/jail_future/he.mdl
models/jail_future/inodoro.mdl
models/jail_future/kevlar.mdl
models/jail_future/lavatorio.mdl
models/jail_future/m249.mdl
models/jail_future/m4a1.mdl
models/jail_future/medkit.mdl
models/jail_future/p90.mdl
models/jail_future/plataforma.mdl
models/jail_future/sg.mdl
sound/jail_future/bandera.wav
sound/jail_future/beep.wav
sound/jail_future/bell.wav
sound/jail_future/blip.wav
sound/jail_future/disparo.wav
sound/jail_future/dissable.wav
sound/jail_future/falla.wav
sound/jail_future/laser.wav
sound/jail_future/pipipi.wav
sound/jail_future/recarga.wav
sprites/jail_future/flash.spr
sprites/jail_future/lightglow.spr
