creditosamogff.wad
halflife.wad
jail_hypnosis_gff.wad
jokenpogff.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
models/GFF/Arvore_1.mdl
models/GFF/gh_tree2.mdl
models/w_m249.mdl
models/w_ak47.mdl
models/w_m4a1.mdl
models/w_awp.mdl
maps/jail_hypnosis_gff.res
maps/jail_hypnosis_gff.bsp

